[ 2025-03-02 16:20:34,330 ] 27 root - INFO - \U0001f52e Prediction Started
[ 2025-03-02 16:20:34,394 ] 31 root - INFO - \u2705 Data loaded successfully. Shape: (5681, 11)
[ 2025-03-02 16:20:34,394 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 16:20:34,419 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 16:20:34,419 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 16:20:34,433 ] 28 root - INFO - Creating new features...
[ 2025-03-02 16:20:34,440 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 16:20:34,506 ] 40 root - INFO - \u2705 Data transformed successfully. Shape: (5681, 37)
[ 2025-03-02 16:20:35,072 ] 31 root - ERROR - \u274c Failed to load model: No module named '_loss'
[ 2025-03-02 16:20:35,073 ] 64 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']
[ 2025-03-02 16:20:35,073 ] 68 root - ERROR - \u274c Prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [47] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']]
[ 2025-03-02 16:24:30,262 ] 27 root - INFO - \U0001f52e Prediction Started
[ 2025-03-02 16:24:30,294 ] 31 root - INFO - \u2705 Data loaded successfully. Shape: (5681, 11)
[ 2025-03-02 16:24:30,295 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 16:24:30,297 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 16:24:30,297 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 16:24:30,307 ] 28 root - INFO - Creating new features...
[ 2025-03-02 16:24:30,313 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 16:24:30,377 ] 40 root - INFO - \u2705 Data transformed successfully. Shape: (5681, 37)
[ 2025-03-02 16:24:30,381 ] 31 root - ERROR - \u274c Failed to load model: No module named '_loss'
[ 2025-03-02 16:24:30,381 ] 64 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']
[ 2025-03-02 16:24:30,381 ] 68 root - ERROR - \u274c Prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [47] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']]
[ 2025-03-02 16:30:57,280 ] 27 root - INFO - \U0001f52e Prediction Started
[ 2025-03-02 16:30:57,309 ] 31 root - INFO - \u2705 Data loaded successfully. Shape: (5681, 11)
[ 2025-03-02 16:30:57,310 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 16:30:57,312 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 16:30:57,312 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 16:30:57,320 ] 28 root - INFO - Creating new features...
[ 2025-03-02 16:30:57,324 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 16:30:57,383 ] 40 root - INFO - \u2705 Data transformed successfully. Shape: (5681, 37)
[ 2025-03-02 16:30:57,387 ] 31 root - ERROR - \u274c Failed to load model: No module named '_loss'
[ 2025-03-02 16:30:57,387 ] 64 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']
[ 2025-03-02 16:30:57,387 ] 68 root - ERROR - \u274c Prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [47] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']]
