[ 2025-03-02 10:25:19,966 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 10:25:19,968 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 10:25:19,968 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 10:25:19,980 ] 28 root - INFO - Creating new features...
[ 2025-03-02 10:25:19,985 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 10:25:20,288 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 10:25:20,288 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 10:25:20,289 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 10:25:20,289 ] 59 root - ERROR - \u274c Model prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [48] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]]
[ 2025-03-02 10:25:20,289 ] 84 root - ERROR - \u274c Client Error: Prediction error.
[ 2025-03-02 10:26:44,074 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 10:26:44,077 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 10:26:44,077 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 10:26:44,087 ] 28 root - INFO - Creating new features...
[ 2025-03-02 10:26:44,093 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 10:26:44,167 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 10:26:44,167 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 10:26:44,167 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 10:26:44,167 ] 59 root - ERROR - \u274c Model prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [48] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]]
[ 2025-03-02 10:26:44,168 ] 84 root - ERROR - \u274c Client Error: Prediction error.
[ 2025-03-02 10:41:13,042 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 10:41:13,044 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 10:41:13,044 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 10:41:13,051 ] 28 root - INFO - Creating new features...
[ 2025-03-02 10:41:13,053 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 10:41:13,108 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 10:41:13,109 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 10:41:13,109 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 10:41:13,109 ] 59 root - ERROR - \u274c Model prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [48] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]]
[ 2025-03-02 10:41:13,109 ] 84 root - ERROR - \u274c Client Error: Prediction error.
[ 2025-03-02 10:41:15,354 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 10:41:15,356 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 10:41:15,356 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 10:41:15,362 ] 28 root - INFO - Creating new features...
[ 2025-03-02 10:41:15,365 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 10:41:15,410 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 10:41:15,411 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 10:41:15,411 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 10:41:15,411 ] 59 root - ERROR - \u274c Model prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [48] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]]
[ 2025-03-02 10:41:15,411 ] 84 root - ERROR - \u274c Client Error: Prediction error.
