[ 2025-03-02 11:22:13,683 ] 27 root - INFO - \U0001f52e Prediction Started
[ 2025-03-02 11:22:13,721 ] 29 root - INFO - \u2705 Data loaded successfully
[ 2025-03-02 11:22:13,721 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 11:22:13,728 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 11:22:13,728 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 11:22:13,738 ] 28 root - INFO - Creating new features...
[ 2025-03-02 11:22:13,749 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 11:22:13,817 ] 31 root - INFO - \u2705 Data transformed successfully
[ 2025-03-02 11:22:14,280 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 11:22:14,281 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 11:22:14,281 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 11:22:14,281 ] 67 root - ERROR - \u274c Prediction failed
